### ISSUE TITLE
Colorized code?

### ISSUE THREAD

**Issue by sliddjur** [fbaligand/vscode-logstash-editor#2]
When I use this addon in visual studio code 1.50.1 I lose all colorized code. Is this working as intended with your extension?

my config:

```
output {
        elasticsearch {
                hosts => [ "127.0.0.1:9200" ]
		index => "logstash-%{+YYYY.MM.dd}"
        }
}
```

And this is what it looks like when vscode autodetects it as "properties"
![image](https://user-images.githubusercontent.com/10002057/98982452-b7098380-251f-11eb-80cf-59660c76168f.png)

**Comment by fbaligand** [comment]
Hi, 

This extension provides completion and documentation, but not colorization.
This is because there is already another plugin that provides colorization for Logstash configuration files:
https://marketplace.visualstudio.com/items?itemName=RandomChance.logstash

So I invite you to install it to have colorization specially for Logstash configuration files.

**Comment by fbaligand** [comment]
I close the issue, as question is answered and there is no feedback since more than 3 months.
