### ISSUE TITLE
Filebeat / Elasticsearch template language mode

### ISSUE THREAD

**Issue by gquintana** [fbaligand/vscode-logstash-editor#4]
For Logstash config files, when the file name doesn't match the expected naming scheme. The work around is to trigger the "Change Language Mode" action and then select "Logstash". This is great.

For Filebeat/Elasticsearch, there is no "Filebeat YAML"  or "Elasticsearch JSON Template" language mode. So if the file name doesn't match the expected naming scheme you're stuck.

**Comment by fbaligand** [comment]
Hi @gquintana,
 
Filebeat configuration has `YAML` language and Elasticsearch index template configuration has `JSON` language.
So as you say, there is no specific language.

That said, in your vscode settings, you can associate your Elasticsearch JSON or Filebeat YAML file to the right JSON schema provided by Logstash Editor.

**For elasticsearch index template:**
- go to vscode "Settings", and search for "json schemas"
- click on "Edit in settings.json"
- define this:
``` json
    "json.schemas": [
        
        {
            "fileMatch": [
                "my-elasticsearch-index-template.json"
            ],
            "url": "https://raw.githubusercontent.com/fbaligand/vscode-logstash-editor/master/jsonschemas/elasticsearch-template-es7x.schema.json"
        }
    ]
``` 

Bonus: since few days, you can associate your elasticsearch index template to a specific Elasticsearch minor version, look here:
https://github.com/fbaligand/vscode-logstash-editor#advanced-tip-choose-elasticsearch-index-template-minor-version

**For Filebeat configuration:**
- go to vscode "Settings", and search for "yaml schemas"
- click on "Edit in settings.json"
- define this:
``` json
    "yaml.schemas": {
        "https://raw.githubusercontent.com/fbaligand/vscode-logstash-editor/master/yamlschemas/filebeat.yml.schema.json": [
            "my-filebeat.yml"
        ]
    }
``` 

Tell me if that answers your need ;)

**Comment by gquintana** [comment]
It works, thanks for your help.

**Comment by fbaligand** [comment]
Nice, thanks for your feedback ;)

**Comment by fbaligand** [comment]
@gquintana 
By the way, a "persistent" way to associate a Logstash conf file pattern to "Logstash" language is to do this:
- Go to vscode "Settings"
- Search for "Files: Associations"
- Click "Add Item"
- Fill "your-logstash-conf-file-pattern" as Key
- Fill "logstash" as Value
- Click "OK" and you're done ;)
